apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: /local/scratch
  nodeSelector:
    noderole: executor
  containers:
    - name: spark-kubernetes-executor
      volumeMounts:
        - name: spark-local-dir-1
          mountPath: /local/scratch
  initContainers:
    - name: volume-permissions
      image: public.ecr.aws/docker/library/busybox
      command: [ 'sh', '-c', 'mkdir /local/scratch; chown -R 999:1000 /local/scratch' ]
      volumeMounts:
        - mountPath: /local/scratch
          name: spark-local-dir-1
